### ISSUE TITLE
Plotly and Plots

### ISSUE THREAD

**Issue by randy-tarnowski** [dirkschumacher/encryptedRmd#10]
Loving the simplicity of this! However, it is not rendering Plotly interactive graphs, which I assume has to do with some way it renders javascript. Any ideas?

**Comment by dirkschumacher** [comment]
Not sure what the problem is, but I would assume one could resolve that issue. Can you provide a _minimal_ example that reproduces the problem?

**Comment by randy-tarnowski** [comment]
Thanks for the quick response. This is a simple rmarkdown script that results in a blank ggplot/plotly. (Excuse the missing three ` at the end, Github markdown shares the notation with the Rmarkdown script


```
---
title: "test"
output: encryptedRmd::encrypted_html_document
---

```{r setup}
library(ggplot2)
library(plotly)
library(encryptedRmd)
df <- data.frame(dose=c("D0.5", "D1", "D2"),
                len=c(4.2, 10, 29.5))
ggplotly(ggplot(data=df, aes(x=dose, y=len)) +
  geom_bar(stat="identity"))
```
```

**Comment by dirkschumacher** [comment]
Before anyone sends a PR. I found a solution that generates a new html document and asks the user to download it. I think that workflow is fine and is less problematic compared to `document.write`
