### ISSUE TITLE
Custom decryption pages

### ISSUE THREAD

**Issue by nacnudus** [dirkschumacher/encryptedRmd#2]
Could it be possible to specify a custom decryption page?  This would enable people to provide:

* Different languages
* Contact details
* Branding

Superb package, I'm really looking forward to using it.

**Comment by derhuerst** [comment]
shameless plug:

I've built this into [`self-decrypting-html-page`](https://github.com/derhuerst/self-decrypting-html-page) `1.1.0`, you can pass a custom HTML template.

Just published [`2.0.1`](https://github.com/derhuerst/self-decrypting-html-page/releases/tag/2.0.1), which has standalone binaries available for download.

**Comment by dirkschumacher** [comment]
In addition, one could implement it here doing the following:

* alter the build-in template to not contain the JS code but to have a placeholder `{{JS}}`
* bundle the JS with the package in the `inst` folder
* change the encryption code to also inject the JS code into the template
* add an option to supply an html file as a template that contains the required placeholders

**Comment by derhuerst** [comment]
Yup, that's the way I implemented it in `self-decrypting-html-page`.
