### ISSUE TITLE
ggplot graphs disappear in encrypted HTML file

### ISSUE THREAD

**Issue by shmoss** [dirkschumacher/encryptedRmd#20]
I'm able to encrypt an HTML file using encryptedRmd:

```
library(encryptedRmd)

path = '//R_Scripts/test.html'

encrypt_html_file(
  path,
  output_path = paste0(path, ".enc.html")
)
```
The encryption works, and I can access the new encrypted HTML. However, none of the ggplots show up in the encrypted version. Tables with data do show up. The test.html document has ggplots that appear perfectly.  

Thanks!

**Comment by dirkschumacher** [comment]
Can you try the current github version? It might be fixed there already. Might be related to #17

**Comment by dirkschumacher** [comment]
Oh, maybe you reference plots in external files? These will not be included into the html file automatically.

**Comment by dirkschumacher** [comment]
I will close it, but feel free to reopen it, if you think it has nothing to do with the two comments above.
