### ISSUE TITLE
R crashing using encrypt_html_file

### ISSUE THREAD

**Issue by HughSt** [dirkschumacher/encryptedRmd#22]
Hi,

When I run `encrypt_html_file` with the file path to the html doc I want to protect, R immediately crashes. I've tried with the CRAN version and GitHub Master. My html file contains a leaflet map (`leaflet` package) which has some interactive features - i.e. you can click on a an area of the map and a popup appears. If I remove the map from the html doc it encrypts fine. Any workarounds available? 

Thanks

**Comment by HughSt** [comment]
Just to update - this actually seems to be something to do with the size of the html file being produced. If I map a fraction of the output it encrypts fine, but with everything it crashes. Seems to happen at around the 5mb size but that's a rough estimate..

**Comment by dirkschumacher** [comment]
Thanks! Interesting. What R version and operating system do you use? Maybe sodium crashes with large inputs?
Can you try the code below and see if that breaks as well?
```R
content <- raw(1e7)
nonce <- sodium::random(24L)
key <- sodium::random(32L)
res <- sodium::data_encrypt(content, key, nonce)
```

**Comment by HughSt** [comment]
I can run that code without any issues.

I'm using R 4.0.2.

Here's the R code for an rmarkdown that causes an issue on my machine

```
library(leaflet)
library(dismo)

# Generate some points
points <- data.frame(x=runif(20000, 0, 50),
                     y=runif(20000, 0, 50))

voronois <- voronoi(points)
leaflet() %>% addTiles() %>% addPolygons(data=voronois,
                                         popup = as.character(voronois$id))

library(DT)
datatable(cars)
```

Cheers, Hugh

**Comment by dirkschumacher** [comment]
Can you try changing the size of `content`? E.g. 1e8, 1e9 etc?

**Comment by dirkschumacher** [comment]
Instead of running `encrypt_html_file`, you could try to run these lines line by line and see where it crashes your session:

https://github.com/dirkschumacher/encryptedRmd/blob/69bedfde29fe76cf6152bf3a2c065a0b59e0f209/R/encrypt_html_file.R#L39-L48

**Comment by HughSt** [comment]
Seems to happen at line 44
```
tpl <- inject_raw_data(tpl, "encrypted", encrypted_content)
```

**Comment by dirkschumacher** [comment]
Interesting. `inject_raw_data` just calls `base::gsub`. 
https://github.com/dirkschumacher/encryptedRmd/blob/69bedfde29fe76cf6152bf3a2c065a0b59e0f209/R/encrypt_html_file.R#L59-L66

Could you also try to run `sodium::bin2hex(encrypted_content)`?
Thanks!

**Comment by HughSt** [comment]
That crashes it too. Did you manage to reproduce the error with my example?

**Comment by dirkschumacher** [comment]
Which one crashes it? Just the `sodium::bin2hex` call? Or `gsub`? No I haven't tried it yet. I just want to work towards the minimal reproducible example that crashes your session, so I can test easier.

**Comment by dirkschumacher** [comment]
So `sodium::bin2hex(1e7)` also crashes my R (4.0.2) session on a mac. I guess we have to report that in the sodium package.

**Comment by dirkschumacher** [comment]
Reported the bug here as well: https://github.com/jeroen/sodium/issues/19

**Comment by dirkschumacher** [comment]
This will be fixed in a new `sodium` package version. Thanks a lot @HughSt for taking the time to report that and to debug the problem!
